import React from "react";
import "./home.css";
import { useOutletContext } from "react-router-dom";
import products from "../data/products";
const productsData = [
    // VEGETABLES
  {
    id: 1,
    name: "Fresh Tomatoes",
    category: "Vegetables",
    price: "40 / kg",
    image: "https://images.pexels.com/photos/533280/pexels-photo-533280.jpeg",
    offer: "10% OFF",
  },
  {
    id: 2,
    name: "Potatoes",
    category: "Vegetables",
    price: "30 / kg",
    image: "https://images.pexels.com/photos/35522608/pexels-photo-35522608.jpeg?cs=srgb&dl=pexels-l-lum-2158594693-35522608.jpg&fm=jpg&_gl=1*pzutog*_ga*NDEzMTEyMDc5LjE3Njc3OTIyNTQ.*_ga_8JE65Q40S6*czE3Njc4NjM4NjQkbzMkZzEkdDE3Njc4NjM5MDAkajI0JGwwJGgw",
    offer: "5% OFF",
  },
  {
    id: 3,
    name: "Onions",
    category: "Vegetables",
    price: "35 / kg",
    image: "https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb",
    offer: "8% OFF",
  },
  {
    id: 4,
    name: "Carrots",
    category: "Vegetables",
    price: "45 / kg",
    image: "https://media.istockphoto.com/id/1334063619/photo/4-pieces-of-orange-carrot-a-japanese-vegetable.jpg?s=2048x2048&w=is&k=20&c=sdlIR2aNECmsxDB4o24iXGmpnN3JWbXRI26ztUW_Hq0=",
    offer: "12% OFF",
  },
  {
    id: 5,
    name: "Cabbage",
    category: "Vegetables",
    price: "50 / kg",
    image: "https://images.pexels.com/photos/12233423/pexels-photo-12233423.jpeg",
    offer: "11% OFF",
  },
  {
    id: 6,
    name: "Broccoli",
    category: "Vegetables",
    price: "60 / kg",
    image: "https://images.pexels.com/photos/7330428/pexels-photo-7330428.jpeg",
    offer: "13% OFF",
  },
   {
    id: 7,
    name: "Cucumber",
    category: "Vegetables",
    price: "40 / kg",
    image: "https://images.pexels.com/photos/17196492/pexels-photo-17196492.jpeg",
    offer: "10% OFF",
  },
   {
    id: 8,
    name: "Bottle Gourd",
    category: "Vegetables",
    price: "50 / kg",
    image: "https://images.pexels.com/photos/11833021/pexels-photo-11833021.jpeg",
    offer: "14% OFF",
  },
   {
    id: 9,
    name: "Spinach",
    category: "Vegetables",
    price: "20 / kg",
    image: "https://images.pexels.com/photos/8845078/pexels-photo-8845078.jpeg",
    offer: "9% OFF",
  },
   {
    id: 10,
    name: "Cauliflower",
    category: "Vegetables",
    price: "60 / kg",
    image: "https://images.pexels.com/photos/22125751/pexels-photo-22125751.jpeg",
    offer: "13% OFF",
  },
  {
    id: 11,
    name: "Beetroot",
    category: "Vegetables",
    price: "70 / kg",
    image: "https://images.pexels.com/photos/29679934/pexels-photo-29679934.jpeg",
    offer: "8% OFF",
  },
    {
    id: 12,
    name: "Brinjal",
    category: "Vegetables",
    price: "35 / kg",
    image: "https://images.pexels.com/photos/6790787/pexels-photo-6790787.jpeg",
    offer: "10% OFF",
  },
  {
    id: 13,
    name: "Ladyfinger",
    category: "Vegetables",
    price: "35 / kg",
    image: "https://images.pexels.com/photos/17975554/pexels-photo-17975554.jpeg",
    offer: "11% OFF",
  },
  {
    id: 14,
    name: "Mushrooms",
    category: "Vegetables",
    price: "55 / kg",
    image: "https://images.pexels.com/photos/33120455/pexels-photo-33120455.jpeg",
    offer: "11% OFF",
  },
 {
    id: 15,
    name: "Mirchi",
    category: "Vegetables",
    price: "15 / kg",
    image: "https://media.istockphoto.com/id/1126390068/photo/dried-red-hot-pepper-whole-dried-chili.jpg?s=2048x2048&w=is&k=20&c=sYD3A4Eh4dIjGLDsT_OdzEdMjx2xwHn1n9msTvUhcLo=",
    offer: "20% OFF",
  },
 {
    id: 16,
    name: "Radish",
    category: "Vegetables",
    price: "25 / kg",
    image: "https://images.pexels.com/photos/33899546/pexels-photo-33899546.jpeg",
    offer: "10% OFF",
  },
  
  {
    id: 17,
    name: "Green Peas",
    category: "Vegetables",
    price: "75 / kg",
    image: "https://images.pexels.com/photos/255469/pexels-photo-255469.jpeg",
    offer: "15% OFF",
  },
    {
    id: 18,
    name: "Sweet Corn",
    category: "Vegetables",
    price: "95 / kg",
    image: "https://images.pexels.com/photos/24595910/pexels-photo-24595910.jpeg",
    offer: "25% OFF",
  },
    {
    id: 19,
    name: "Bitter Gourd",
    category: "Vegetables",
    price: "15 / kg",
    image: "https://images.pexels.com/photos/33176798/pexels-photo-33176798.jpeg",
    offer: "5% OFF",
  },


  // FRUITS
  {
    id: 20,
    name: "Apples",
    category: "Fruits",
    price: "120 / kg",
    image: "https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6",
    offer: "15% OFF",
  },
  {
    id: 21,
    name: "Bananas",
    category: "Fruits",
    price: "50 / dozen",
    image: "https://images.pexels.com/photos/18840180/pexels-photo-18840180.jpeg",
    offer: "5% OFF",
  },
  {
    id: 22,
    name: "Oranges",
    category: "Fruits",
    price: "80 / kg",
    image: "https://images.pexels.com/photos/14655678/pexels-photo-14655678.jpeg",
    offer: "10% OFF",
  },
  {
    id: 23,
    name: "Grapes",
    category: "Fruits",
    price: "90 / kg",
    image: "https://images.pexels.com/photos/33344322/pexels-photo-33344322.jpeg",
    offer: "7% OFF",
  },
  {
    id: 24,
    name: "Mangoes",
    category: "Fruits",
    price: "100 / kg",
    image: "https://images.pexels.com/photos/7543212/pexels-photo-7543212.jpeg",
    offer: "5% OFF",
  },
   {
    id: 25,
    name: "Guava",
    category: "Fruits",
    price: "80 / kg",
    image: "https://images.pexels.com/photos/2351813/pexels-photo-2351813.jpeg",
    offer: "6% OFF",
  },
   {
    id: 26,
    name: "Green Apple",
    category: "Fruits",
    price: "85 / kg",
    image: "https://images.pexels.com/photos/693794/pexels-photo-693794.jpeg",
    offer: "3% OFF",
  },
    {
    id: 27,
    name: "Pineapple",
    category: "Fruits",
    price: "125 / kg",
    image: "https://images.pexels.com/photos/32083199/pexels-photo-32083199.jpeg",
    offer: "5% OFF",
  },
     {
    id: 28,
    name: "Papaya",
    category: "Fruits",
    price: "105 / kg",
    image: "https://images.pexels.com/photos/4113802/pexels-photo-4113802.jpeg",
    offer: "6% OFF",
  },
    {
    id: 29,
    name: "Kiwi",
    category: "Fruits",
    price: "200 / kg",
    image: "https://images.pexels.com/photos/6719339/pexels-photo-6719339.jpeg",
    offer: "9% OFF",
  },
  {
    id: 30,
    name: "Strawberries",
    category: "Fruits",
    price: "60 / kg",
    image: "https://images.pexels.com/photos/6246733/pexels-photo-6246733.jpeg",
    offer: "2% OFF",
  },
    {
    id: 31,
    name: "Blueberries",
    category: "Fruits",
    price: "70 / kg",
    image: "https://images.pexels.com/photos/2539174/pexels-photo-2539174.jpeg",
    offer: "2% OFF",
  },
    {
    id: 32,
    name: "Blackberries",
    category: "Fruits",
    price: "80 / kg",
    image: "https://images.pexels.com/photos/27644257/pexels-photo-27644257.jpeg",
    offer: "2% OFF",
  },
   {
    id: 33,
    name: "Pomegranates",
    category: "Fruits",
    price: "120 / kg",
    image: "https://images.pexels.com/photos/17856915/pexels-photo-17856915.jpeg",
    offer: "5% OFF",
  },
 {
    id: 34,
    name: "Cherries",
    category: "Fruits",
    price: "100 / kg",
    image: "https://images.pexels.com/photos/8357979/pexels-photo-8357979.jpeg",
    offer: "7% OFF",
  },
   {
    id: 35,
    name: "Lychees",
    category: "Fruits",
    price: "90 / kg",
    image: "https://images.pexels.com/photos/15221058/pexels-photo-15221058.jpeg",
    offer: "4% OFF",
  },
   {
    id: 36,
    name: "Dragon Fruit",
    category: "Fruits",
    price: "150 / kg",
    image: "https://images.pexels.com/photos/1437598/pexels-photo-1437598.jpeg",
    offer: "5% OFF",
  },
 {
    id: 37,
    name: "Avocado",
    category: "Fruits",
    price: "130 / kg",
    image: "https://images.pexels.com/photos/3029520/pexels-photo-3029520.jpeg",
    offer: "3% OFF",
  },
   {
    id: 38,
    name: "Jackfruit",
    category: "Fruits",
    price: "180 / kg",
    image: "https://images.pexels.com/photos/31782674/pexels-photo-31782674.jpeg",
    offer: "7% OFF",
  },
 {
    id: 39,
    name: "Durian",
    category: "Fruits",
    price: "280 / kg",
    image: "https://images.pexels.com/photos/11493641/pexels-photo-11493641.jpeg",
    offer: "2% OFF",
  },
   {
    id: 40,
    name: "Watermelon",
    category: "Fruits",
    price: "100 / kg",
    image: "https://images.pexels.com/photos/7898007/pexels-photo-7898007.jpeg",
    offer: "2% OFF",
  },
  // SNACKS
  {
    id: 41,
    name: "Potato Chips",
    category: "Snacks",
    price: "20",
    image: "https://images.pexels.com/photos/13060680/pexels-photo-13060680.jpeg",
    offer: "10% OFF",
  },
  {
    id: 42,
    name: "Biscuits",
    category: "Snacks",
    price: "25",
    image: "https://images.pexels.com/photos/20558713/pexels-photo-20558713.jpeg",
    offer: "6% OFF",
  },
  {
    id: 43,
    name: "Chocolates",
    category: "Snacks",
    price: "40",
    image: "https://images.pexels.com/photos/33239/halloween-candy-chocolates-nuts-sweet.jpg",
    offer: "12% OFF",
  },
  {
    id: 44,
    name: "Popcorn",
    category: "Snacks",
    price: "30",
    image: "https://images.pexels.com/photos/33129/popcorn-movie-party-entertainment.jpg",
    offer: "8% OFF",
  },
   {
    id: 45,
    name: "Nuts Mix",
    category: "Snacks",
    price: "50",
    image: "https://images.pexels.com/photos/5507656/pexels-photo-5507656.jpeg",
    offer: "7% OFF",
  },
 {
    id: 46,
    name: "Ice Cream",
    category: "Snacks",
    price: "50",
    image: "https://images.pexels.com/photos/11441807/pexels-photo-11441807.jpeg",
    offer: "7% OFF",
  },
 {
    id: 47,
    name: "French Fries",
    category: "Snacks",
    price: "100",
    image: "https://images.pexels.com/photos/12548553/pexels-photo-12548553.jpeg",
    offer: "8% OFF",
  },
   {
    id: 48,
    name: "Bread",
    category: "Snacks",
    price: "70",
    image: "https://images.pexels.com/photos/19953729/pexels-photo-19953729.jpeg",
    offer: "5% OFF",
  },
  {
    id: 49,
    name: "Buns",
    category: "Snacks",
    price: "50",
    image: "https://images.pexels.com/photos/4775241/pexels-photo-4775241.jpeg",
    offer: "3% OFF",
  },
  {
    id: 50,
    name: "Cookies",
    category: "Snacks",
    price: "150",
    image: "https://images.pexels.com/photos/4051603/pexels-photo-4051603.jpeg",
    offer: "8% OFF",
  },
{
    id: 51,
    name: "Muffins",
    category: "Snacks",
    price: "80",
    image: "https://images.pexels.com/photos/10509252/pexels-photo-10509252.jpeg",
    offer: "2% OFF",
  },
  {
    id: 52,
    name: "Cupcakes",
    category: "Snacks",
    price: "120",
    image: "https://images.pexels.com/photos/7140433/pexels-photo-7140433.jpeg",
    offer: "5% OFF",
  },
   {
    id: 53,
    name: "Doughnuts",
    category: "Snacks",
    price: "70",
    image: "https://images.pexels.com/photos/1407346/pexels-photo-1407346.jpeg",
    offer: "3% OFF",
  },
{
    id: 54,
    name: "Burger",
    category: "Snacks",
    price: "70",
    image: "https://images.pexels.com/photos/1600727/pexels-photo-1600727.jpeg",
    offer: "4% OFF",
  },
  {
    id: 55,
    name: "Gulab Jamun",
    category: "Snacks",
    price: "50",
    image: "https://images.pexels.com/photos/7406887/pexels-photo-7406887.jpeg",
    offer: "2% OFF",
  },
   {
    id: 56,
    name: "Pani Puri",
    category: "Snacks",
    price: "50 ",
    image: "https://images.pexels.com/photos/35008223/pexels-photo-35008223.jpeg",
    offer: "2% OFF",
  },
  {
    id: 57,
    name: "Jam",
    category: "Snacks",
    price: "10",
    image: "https://images.pexels.com/photos/2113556/pexels-photo-2113556.jpeg",
    offer: "2% OFF",
  },
   {
    id: 58,
    name: "Honey",
    category: "Snacks",
    price: "200",
    image: "https://images.pexels.com/photos/33260/honey-sweet-syrup-organic.jpg",
    offer: "7% OFF",
  },
{
    id: 59,
    name: "Maple Syrup",
    category: "Snacks",
    price: "100",
    image: "https://images.pexels.com/photos/2059357/pexels-photo-2059357.jpeg",
    offer: "4% OFF",
  },
  {
    id: 60,
    name: "Chocolate Spread",
    category: "Snacks",
    price: "150",
    image: "https://images.pexels.com/photos/14459543/pexels-photo-14459543.jpeg",
    offer: "5% OFF",
  },
  {
    id: 61,
    name: "Cake",
    category: "Snacks",
    price: "150",
    image: "https://images.pexels.com/photos/6557291/pexels-photo-6557291.jpeg",
    offer: "3% OFF",
  },

  // GROCERIES
  {
    id: 62,
    name: "Basmati Rice",
    category: "Groceries",
    price: "80 / kg",
    image: "https://images.pexels.com/photos/35552985/pexels-photo-35552985.jpeg",
    offer: "12% OFF",
  },
  {
    id: 63,
    name: "Wheat Flour",
    category: "Groceries",
    price: "55 / kg",
    image: "https://media.istockphoto.com/id/186831897/photo/flour-and-wheat-grains.jpg?s=2048x2048&w=is&k=20&c=yKwnrsL3XyPp9MkpjT7HibzKey8EHy1pcm_8TrDwdRk=",
    offer: "10% OFF",
  },
  {
    id: 64,
    name: "Cooking Oil",
    category: "Groceries",
    price: "140 / L",
    image: "https://images.pexels.com/photos/4910221/pexels-photo-4910221.jpeg",
    offer: "9% OFF",
  },
  {
    id: 65,
    name: "Sugar",
    category: "Groceries",
    price: "45 / kg",
    image: "https://images.pexels.com/photos/9974510/pexels-photo-9974510.jpeg",
    offer: "6% OFF",
  },
   {
    id: 66,
    name: "Rice",
    category: "Groceries",
    price: "100 / kg",
    image: "https://images.pexels.com/photos/15879424/pexels-photo-15879424.jpeg",
    offer: "10% OFF",
  },
  {
    id: 67,
    name: "Roti Flour",
    category: "Groceries",
    price: "50 / kg",
    image: "https://images.pexels.com/photos/8136893/pexels-photo-8136893.jpeg",
    offer: "9% OFF",
  },
  {
    id: 68,
    name: "Coconut Oil",
    category: "Groceries",
    price: "60 / L",
    image: "https://images.pexels.com/photos/31401740/pexels-photo-31401740.jpeg",
    offer: "4% OFF",
  },
  {
    id: 69,
    name: "Soaps",
    category: "Groceries",
    price: "45 / kg",
    image: "https://images.pexels.com/photos/1460839/pexels-photo-1460839.jpeg",
    offer: "4% OFF",
  },
   {
    id: 70,
    name: "Salt",
    category: "Groceries",
    price: "10 / kg",
    image: "https://media.istockphoto.com/id/504609766/photo/white-sugar-in-wood-spoon.jpg?s=2048x2048&w=is&k=20&c=q3D17gKEVHi6llOgWmO0azkDHBDr17w1B0_aBVdkEgw=",
    offer: "12% OFF",
  },
  {
    id: 71,
    name: "Chili Powder",
    category: "Groceries",
    price: "100 / kg",
    image: "https://images.pexels.com/photos/33440709/pexels-photo-33440709.jpeg",
    offer: "8% OFF",
  },
  {
    id: 72,
    name: "Sunflower Oil",
    category: "Groceries",
    price: "340 / L",
    image: "https://images.pexels.com/photos/9005713/pexels-photo-9005713.jpeg",
    offer: "8% OFF",
  },
  {
    id: 73,
    name: "Turmeric Powder",
    category: "Groceries",
    price: "55 / kg",
    image: "https://media.istockphoto.com/id/636406412/photo/turmeric-powder-on-wooden-bowl-top-view.jpg?s=2048x2048&w=is&k=20&c=ExDe-Vk5uulhB0JXl8evlLmlm-8rbzEYjbXhz3tIKJM=",
    offer: "3% OFF",
  },
    {
    id: 74,
    name: "Ginger",
    category: "Groceries",
    price: "56 / kg",
    image: "https://images.pexels.com/photos/161556/ginger-plant-asia-rhizome-161556.jpeg",
    offer: "4% OFF",
  },
    {
    id: 75,
    name: "Garlic",
    category: "Groceries",
    price: "60 / kg",
    image: "https://images.pexels.com/photos/19127227/pexels-photo-19127227.jpeg",
    offer: "5% OFF",
  },
    {
    id: 76,
    name: "Knife",
    category: "Groceries",
    price: "30 / kg",
    image: "https://images.pexels.com/photos/203559/pexels-photo-203559.jpeg",
    offer: "2% OFF",
  },
   {
    id: 77,
    name: "Spoons",
    category: "Groceries",
    price: "50 / kg",
    image: "https://images.pexels.com/photos/10915543/pexels-photo-10915543.jpeg",
    offer: "7% OFF",
  },
   {
    id: 78,
    name: "Bowls",
    category: "Groceries",
    price: "100",
    image: "https://images.pexels.com/photos/6611425/pexels-photo-6611425.jpeg",
    offer: "8% OFF",
  },
     {
    id: 79,
    name: "Plates",
    category: "Groceries",
    price: "150",
    image: "https://media.istockphoto.com/id/144336965/photo/multi-colored-plates-stack.jpg?s=2048x2048&w=is&k=20&c=Hm3qe61imoBJ2AFANNIErhUbfAa7XPEm9diGtxJWakc=",
    offer: "2% OFF",
  },
   {
    id: 80,
    name: "Cups",
    category: "Groceries",
    price: "250",
    image: "https://images.pexels.com/photos/14299945/pexels-photo-14299945.jpeg",
    offer: "3% OFF",
  },
  {
    id: 81,
    name: "Coffee Powder",
    category: "Groceries",
    price: "60 / kg",
    image: "https://images.pexels.com/photos/11289694/pexels-photo-11289694.jpeg",
    offer: "5% OFF",
  },
   {
    id: 82,
    name: "Maggi ",
    category: "Groceries",
    price: "30 / kg",
    image: "https://media.istockphoto.com/id/1899435835/photo/curry-noodles-with-egg-green-vegetable-and-spicy-broth.jpg?s=2048x2048&w=is&k=20&c=kOCULxcczSRcjt_GQkiM4dwfn6IrEI8iauzINdPGufM=",
    offer: "9% OFF",
  },
     {
    id: 83,
    name: "Masala Powder ",
    category: "Groceries",
    price: "120 / kg",
    image: "https://images.pexels.com/photos/32830296/pexels-photo-32830296.jpeg",
    offer: "7% OFF",
  },
    {
    id: 84,
    name: " Milk ",
    category: "Groceries",
    price: "100 / L",
    image: "https://images.pexels.com/photos/5967316/pexels-photo-5967316.jpeg",
    offer: "2% OFF",
  },
   {
    id: 85,
    name: " Bags ",
    category: "Groceries",
    price: "350 ",
    image: "https://images.pexels.com/photos/219023/pexels-photo-219023.jpeg",
    offer: "4% OFF",
  },
  {
    id: 86,
    name: " Detergent ",
    category: "Groceries",
    price: "250  / L",
    image: "https://images.pexels.com/photos/5217897/pexels-photo-5217897.jpeg",
    offer: "2% OFF",
  },
   {
    id: 87,
    name: " Dishwash ",
    category: "Groceries",
    price: "550 ",
    image: "https://images.pexels.com/photos/5217779/pexels-photo-5217779.jpeg",
    offer: "3% OFF",
  },
  {
    id: 88,
    name: " Floor mats",
    category: "Groceries",
    price: "250 / Pair",
    image: "https://images.pexels.com/photos/8831719/pexels-photo-8831719.jpeg",
    offer: "7% OFF",
  },
  {
    id: 89,
    name: " Handwash",
    category: "Groceries",
    price: "150 / L",
    image: "https://images.pexels.com/photos/3963095/pexels-photo-3963095.jpeg",
    offer: "5% OFF",
  },
   {
    id: 90,
    name: " Shampoo",
    category: "Groceries",
    price: "250 / L",
    image: "https://images.pexels.com/photos/3735657/pexels-photo-3735657.jpeg",
    offer: "2% OFF",
  },

];

const Home = () => {
  const {
    selectedCategory,
    cartItems,
    addToCart,
    removeFromCart,
  } = useOutletContext();

  const filteredProducts =
    selectedCategory === "All"
      ? productsData
      : productsData.filter(
          (item) => item.category === selectedCategory
        );

  const getCartItem = (id) =>
    cartItems.find((item) => item.id === id);

  return (
    <div className="products">
      {filteredProducts.map((product) => {
        const cartItem = getCartItem(product.id);

        return (
          <div key={product.id} className="card">
            <img src={product.image} alt={product.name} />
            <h4>{product.name}</h4>
            <p>₹{product.price}</p>

            {cartItem ? (
              <div>
                <button onClick={() => removeFromCart(product.id)}>-</button>
                <span>{cartItem.qty}</span>
                <button onClick={() => addToCart(product)}>+</button>
              </div>
            ) : (
              <button onClick={() => addToCart(product)}>
                Add to Cart
              </button>
            )}
          </div>
        );
      })}
    </div>
  );
};

export default Home;
